---
# Source: traefik/templates/rbac/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: my-traefik
  namespace: default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: my-traefik-default
    helm.sh/chart: traefik-35.2.0
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: false
